export default {
    FILTERS_DATA: 'FILTERS_DATA',
    FILTERS_RESULTS_RESET: 'FILTERS_RESULTS_RESET',
    FILTERS_FAILED: 'FILTERS_FAILED',
    BYO_FILTERS_FAILED: 'BYO_FILTERS_FAILED',
    IS_FILTER_SELECTED: 'IS_FILTER_SELECTED',
    SHOW_SORT_OPTIONS: 'SHOW_SORT_OPTIONS',
    SUPRESS_MARKETING_TILE: 'SUPRESS_MARKETING_TILE',
    NO_FILTERS: 'NO_FILTERS',
    UPDATED_SELECTED_FILTERS: 'UPDATED_SELECTED_FILTERS',
    ENDECA_DIMENSIONIDS: {
        CATEGORIES: 1,
        DESIGNERS_COLLECTIONS: 2,
        COLLECTIONS: 3,
        PRICE_RANGES: 4,
        MATERIALS: 5,
        GEMSTONES: 6,
        GEMSTONECOLOR: 14,
        COLOR: 22,
        SETTING: 24,
        DIAMONSHAPE: 27,
        BANDS: 30
    }
};
