export default {
    CHANGE_STORE_STATUS: 'CHANGE_STORE_STATUS',
    STORE_DETAIL_STATUS: 'STORE_DETAIL_STATUS',
    STORE_DETAIL: 'STORE_DETAIL',
    STORE_SEARCH: 'STORE_SEARCH',
    STORE_SEARCH_SUCCESS: 'STORE_SEARCH_SUCCESS',
    FROM_STORE_SEARCH: 'FROM_STORE_SEARCH',
    STORE_SEARCHED_FOR: 'STORE_SEARCHED_FOR',
    SELECTED_STORE_DETAILS: 'SELECTED_STORE_DETAILS',
    RADIUS_CHOOSED: 'RADIUS_CHOOSED',
    SET_SELECTED_REGION: 'SET_SELECTED_REGION',
    STORE_SEARCH_API_FAILURE: 'STORE_SEARCH_API_FAILURE',
    SET_GEO_LOCATION: 'SET_GEO_LOCATION',
    SET_GEO_LOCATION_BLOCKED: 'SET_GEO_LOCATION_BLOCKED'
};
