export default {
    ITEM_GROUP_COMPLETE_SUCCESS: 'ITEM_GROUP_COMPLETE_SUCCESS',
    CLEAR_ON_HOVER: 'CLEAR_ON_HOVER',
    PRODUCT_SELECTED: 'PRODUCT_SELECTED',
    BYO_GROUP_COMPLETE_SUCCESS: 'BYO_GROUP_COMPLETE_SUCCESS'
};
