export default {
    TYPE: {
        SKU: 'SKU',
        CATEGORY: 'CATEGORY',
        GROUP: 'GROUP',
        ITEM_COMPLETE: 'ITEM_COMPLETE',
        GROUP_COMPLETE: 'GROUP_COMPLETE',
        BYO_GROUP_COMPLETE: 'BYO_GROUP_COMPLETE'
    },
    CAROUSEL_TYPE: {
        SKU_CAT: 'SKU_CAT',
        RICH_REL: 'RICH_REL'
    },
    BROWSE_GRID: {
        PRODUCT_TILE_LAYOUT: 'layout_1x1',
        LAYOUT: 'layout_',
        MOBILE_LAYOUT: 'mobile_layout_'
    },
    FETCH_PRODUCT_PRICE_SUCCESS: 'FETCH_PRODUCT_PRICE_SUCCESS',
    UPDATE_PRODUCT_PRICE: 'UPDATE_PRODUCT_PRICE',
    UPDATE_SELECTED_PRODUCT_QUANTITY: 'UPDATE_SELECTED_PRODUCT_QUANTITY',
    ADD_TO_BAG_SUCCESS: 'ADD_TO_BAG_SUCCESS',
    ADD_TO_BAG_MAX_QUANTITY_FAILURE: 'ADD_TO_BAG_MAX_QUANTITY_FAILURE',
    MEDIA: {
        STRAIGHT_ON: 'SKUSTRAIGHTON',
        ALTERNATE_VIEW: 'SKUALTERNATEVIEW'
    }
};
