export default {
    SALES_SERVICE_SUCCESS: 'SALES_SERVICE_SUCCESS',
    DISTRIBUTION_INVENTORY_SUCCESS: 'DISTRIBUTION_INVENTORY_SUCCESS',
    ORDER_STATUS: 'orderStatus',
    RETAIL_STORE: 'retailStore',
    DISTRIBUTION_CENTER: 'distributionCenter',
    ON_ORDER_STATUS_SUCCESS: 'ON_ORDER_STATUS_SUCCESS',
    COLUMN_HEADINGS: 'COLUMN_HEADINGS',
    ALL_STORES: 'ALL_STORES',
    STORES_RETAIL_INVENTORY: 'STORES_RETAIL_INVENTORY',
    STORES_RETAIL_INVENTORY_FAILED: 'STORES_RETAIL_INVENTORY_FAILED',
    RESET_RETAIL_STORE_RESULTS: 'RESET_RETAIL_STORE_RESULTS'
};
