export default {
    STORES_UPDATED: 'STORES_UPDATED',
    VISIBLE_STORES_UPDATED: 'VISIBLE_STORES_UPDATED',
    STORES_SEARCH_DATA_UPDATED: 'STORES_SEARCH_DATA_UPDATED',
    STORES_SEARCH_RESPONSE_DATA: 'STORES_SEARCH_RESPONSE_DATA',
    STORES_SEARCH_NO_RESULTS_DATA: 'STORES_SEARCH_NO_RESULTS_DATA'
};
