export default {
    WISHLIST_FETCHED: 'WISHLIST_FETCHED',
    WISHLIST_DELETE: 'WISHLIST_DELETE',
    WISHLIST_FAILED: 'WISHLIST_FAILED',
    CUSTOM_WISHLIST_FETCHED: 'CUSTOM_WISHLIST_FETCHED',
    CUSTOM_WISHLIST_FAILED: 'CUSTOM_WISHLIST_FAILED'
};
