// @flow

export type ByoFilterDimensionValue = {
    count: number,
    displayOrder: string,
    id: number,
    isMultiSelect: boolean,
    lineBreakGroupID: string,
    name: string,
    selected: string,
    urluniqueId: string
}

export type ByoFilterDimension = {
    dimensionValues: Array<ByoFilterDimensionValue>,
    endecaDimensionId: number,
    groupName: string,
    isHidden: boolean
};

export type MediaStichPosition = {
    seqNum: number,
    xCoords: number,
    yCoords: number
};

export type ByoGuidedProduct = {
    additionalImageUrls: Array<string>,
    byoItemProductType: string,
    class: string,
    crop: string,
    defaultSku: string,
    department: string,
    displayOrder: number,
    engravingQuantity: string,
    fixtureItemMedia: string,
    formattedTitle: string,
    friendlyUrl: string,
    groupMemberImageUrls: Array<any>,
    imageURL: string,
    isAvailableOnline: boolean,
    isByoEngravable: boolean,
    isGroup: boolean,
    isIRExperience: boolean,
    isLowInventory: boolean,
    isMotifEnabled: boolean,
    isNewProduct: boolean,
    isPurchasable: boolean,
    isRelevance: boolean,
    isServiceable: boolean,
    itemTypeID: string,
    leafDefaultSku: string,
    mediaStichPositions: Array<MediaStichPosition>,
    mipsDescription: string,
    moduleTypeID: string,
    mountTypes: Array<number>,
    name: string,
    posDescription: string,
    price: string,
    productTypeDescription: string,
    rrClickTrackingURL: string,
    serviceTypes: Array<any>,
    sharpen: string,
    sharpenL: string,
    showEmailWhenAvailable: boolean,
    sku: string,
    sortOrderEndeca: string,
    sortOrderRR: string,
    style: string,
    title: string,
    titleSplit: Array<string>
};

export type ByoGuidedResponse = {
    dimensions: Array<ByoFilterDimension>,
    imagePreset: string,
    imageUrlFormat: string,
    maxPrice: string,
    minPrice: string,
    numofRecords: number,
    products: Array<ByoGuidedProduct>,
    relevancySortOrder: string,
    searchEngine: string
};

export type ByoGroupObject = {
    additionalInfo: string,
    assortmentId: number,
    canonicalCategoryId: number,
    canonicalCategoryName: string,
    canonicalCategoryUrlUniqueId: string,
    canonicalMasterCategoryId: number,
    canonicalMasterCategoryName: string,
    canonicalMasterCategoryUrlUniqueId: string,
    class: string,
    classDescription: string,
    companyId: number,
    dateUpdated: string,
    department: number,
    departmentDescription: string,
    discontinuedWithInventory: boolean,
    formattedPrice: string,
    groupCustomType: number,
    groupCustomTypeName: string,
    hidePurchaseWithLowInventoryItem: boolean,
    isBOPS: boolean,
    isBYOEnabled: boolean,
    isFIISEnabled: boolean,
    isGroup: boolean,
    isLowInventory: boolean,
    isNew: boolean,
    isPartialShip: boolean,
    isPriceAvailable: boolean,
    isPurchasable: boolean,
    isRemoveFromAssortment: boolean,
    isRingSizeChartVisible: boolean,
    isRingSizeGuideVisible: boolean,
    isRingSizeVisible: boolean,
    isServiceable: boolean,
    isShowInBrowse: boolean,
    isShowInEmployeeBrowse: boolean,
    isShowInEmployeeSearch: boolean,
    isShowInSearch: boolean,
    isShownonpurchasableitemprice: boolean,
    isSoldIr: boolean,
    isSpinsetAvailable: boolean,
    lineListFormatTypeId: number,
    lineListLabel: string,
    longDescription: string,
    maxQuantityLimit: number,
    measuringYourWristLinkVisible: boolean,
    mipsDescription: string,
    posDescription: string,
    price: number,
    selectedSku: string,
    shippingType: number,
    shortDescription: string,
    showInBrowseAndSearchStartTime: string,
    showNonPurchasableItemPrice: boolean,
    siteId: number,
    sku: string,
    specifications: string,
    style: string,
    styleDescription: string,
    taxabilityCode: string,
    title: string,
    titleSplit: Array<string>,
    urluniqueId: string,
}

export type ByoGroupAttributes = {
    assortmentId: number,
    dateLastModified: string,
    existLowInventoryItem: boolean,
    groupCustomTypeId: number,
    groupDefaultItemSku: string,
    groupDefaultSkuInRetailMode: string,
    groupDropDownLabel: string,
    groupTypeID: number,
    hidePurchasewithLowInventoryItem: boolean,
    isColorSwatch: boolean,
    siteId: number,
    sku: string,
    useDefaultItemCustomMedia: boolean,
    useGroupDefaultItemAdditionalInfo: boolean,
    useGroupDefaultItemLongDescription: boolean,
    useGroupDefaultItemMedia: boolean,
    useGroupDefaultItemShortDescription: boolean,
    useGroupDefaultItemSpecifications: boolean,
    useGroupDefaultItemTitle: boolean,
}

export type ByoGroupItemMediaInner = {
    assortmentId: number,
    dateLastModified: string,
    displayOrder: number,
    isIntranet: boolean,
    isVisible: boolean,
    mediaFileName: string,
    mediaType: number,
    mediaTypeID: number,
    mediaTypeName: string,
    removeFromAssortment: boolean,
    siteId: number,
    sku: string
}

export type ByoGroupItemMedia = {
    colorSwatchImageUrlFormat: string,
    imagePrefix: string,
    imagePreset: string,
    imageUrlFormat: string,
    itemMedia: Array<ByoGroupItemMediaInner>,
    noImagePreset: string,
    noImageUrlFormat: string,
    pkbAppSavedItemPreset: string,
}

export type ByoGroupItem = {
    canonicalURL: string,
    dateCreated: string,
    department: number,
    displayOrder: number,
    formattedPrice: string,
    friendlyURL: string,
    groupSku: string,
    isDiscontinuedWithInventory: boolean,
    isGroup: boolean,
    isLowInventory: boolean,
    isNew: boolean,
    itemMedia: ByoGroupItemMedia,
    linkText: string,
    maxQuantityLimit: number,
    memberItemFriendlyURL: string,
    memberSku: string,
    price: number,
    removeFromAssortment: boolean
}

export type ByoGroupSearchAttribute = {
    displayOrder: number,
    endecaDimensionId: number,
    endecaDimensionName: string,
    endecaDvalId: string,
    searchAttributeId: number,
    searchAttributeName: string,
    urluniqueId: string
}

export type ByoGroupResponse = {
    canonicalURL: string,
    friendlyURL: string,
    group: ByoGroupObject,
    groupAttributes: ByoGroupAttributes,
    groupItems: Array<ByoGroupItem>,
    isSpinsetAvailable: boolean,
    searchAttributes: Array<ByoGroupSearchAttribute>,
    siteId: number
}
